changelog:
  categories:
    - title: 🚨 Breaking Changes
      labels:
        - breaking-change

    - title: 🔒 Security
      labels:
        - security

    - title: 🚀 Features
      labels:
        - feature
        - enhancement

    - title: 🐛 Bug fixes
      labels:
        - bugfix

    - title: 📚 Documentation
      labels:
        - documentation

    - title: 🌐 Translations
      labels:
        - translation

    - title: 🔨 Maintenance
      labels:
        - maintenance
        - tech-debt
        - chore

    - title: 🤖 Dependencies
      labels:
        - dependencies

    - title: 💤 Other changes
      labels:
        - '*'
