version: "3.8"

# Hardware acceleration for transcoding using RKMPP for Rockchip SOCs
# This is only needed if you want to use hardware acceleration for transcoding.
# Supported host OS is Ubuntu Jammy 22.04 with custom ffmpeg from ppa:liujianfeng1994/rockchip-multimedia

services:
  hwaccel:
    privileged: true
    group_add:
      - video
    devices:
      - /dev/rga:/dev/rga
      - /dev/dri:/dev/dri
      - /dev/dma_heap:/dev/dma_heap
      - /dev/mpp_service:/dev/mpp_service
    volumes:
      - /lib/firmware/mali_csffw.bin:/lib/firmware/mali_csffw.bin:ro
      - /usr/bin/ffmpeg:/usr/bin/ffmpeg_mpp:ro
      - /lib/aarch64-linux-gnu/libavdevice.so.60:/lib/aarch64-linux-gnu/libavdevice.so.60:ro
      - /lib/aarch64-linux-gnu/libavfilter.so.9:/lib/aarch64-linux-gnu/libavfilter.so.9:ro
      - /lib/aarch64-linux-gnu/libavformat.so.60:/lib/aarch64-linux-gnu/libavformat.so.60:ro
      - /lib/aarch64-linux-gnu/libavcodec.so.60:/lib/aarch64-linux-gnu/libavcodec.so.60:ro
      - /lib/aarch64-linux-gnu/libpostproc.so.57:/lib/aarch64-linux-gnu/libpostproc.so.57:ro
      - /lib/aarch64-linux-gnu/libswresample.so.4:/lib/aarch64-linux-gnu/libswresample.so.4:ro
      - /lib/aarch64-linux-gnu/libswscale.so.7:/lib/aarch64-linux-gnu/libswscale.so.7:ro
      - /lib/aarch64-linux-gnu/libavutil.so.58:/lib/aarch64-linux-gnu/libavutil.so.58:ro
      - /lib/aarch64-linux-gnu/libapparmor.so.1:/lib/aarch64-linux-gnu/libapparmor.so.1:ro
      - /lib/aarch64-linux-gnu/libasound.so.2:/lib/aarch64-linux-gnu/libasound.so.2:ro
      - /lib/aarch64-linux-gnu/libass.so.9:/lib/aarch64-linux-gnu/libass.so.9:ro
      - /lib/aarch64-linux-gnu/libasyncns.so.0:/lib/aarch64-linux-gnu/libasyncns.so.0:ro
      - /lib/aarch64-linux-gnu/libavc1394.so.0:/lib/aarch64-linux-gnu/libavc1394.so.0:ro
      - /lib/aarch64-linux-gnu/libavcodec.so.58:/lib/aarch64-linux-gnu/libavcodec.so.58:ro
      - /lib/aarch64-linux-gnu/libavutil.so.56:/lib/aarch64-linux-gnu/libavutil.so.56:ro
      - /lib/aarch64-linux-gnu/libblas.so.3:/lib/aarch64-linux-gnu/libblas.so.3:ro
      - /lib/aarch64-linux-gnu/libbluray.so.2:/lib/aarch64-linux-gnu/libbluray.so.2:ro
      - /lib/aarch64-linux-gnu/libbs2b.so.0:/lib/aarch64-linux-gnu/libbs2b.so.0:ro
      - /lib/aarch64-linux-gnu/libcaca.so.0:/lib/aarch64-linux-gnu/libcaca.so.0:ro
      - /lib/aarch64-linux-gnu/libcdio_cdda.so.2:/lib/aarch64-linux-gnu/libcdio_cdda.so.2:ro
      - /lib/aarch64-linux-gnu/libcdio_paranoia.so.2:/lib/aarch64-linux-gnu/libcdio_paranoia.so.2:ro
      - /lib/aarch64-linux-gnu/libcdio.so.19:/lib/aarch64-linux-gnu/libcdio.so.19:ro
      - /lib/aarch64-linux-gnu/libchromaprint.so.1:/lib/aarch64-linux-gnu/libchromaprint.so.1:ro
      - /lib/aarch64-linux-gnu/libcjson.so.1:/lib/aarch64-linux-gnu/libcjson.so.1:ro
      - /lib/aarch64-linux-gnu/libcodec2.so.1.0:/lib/aarch64-linux-gnu/libcodec2.so.1.0:ro
      - /lib/aarch64-linux-gnu/libdav1d.so.5:/lib/aarch64-linux-gnu/libdav1d.so.5:ro
      - /lib/aarch64-linux-gnu/libdbus-1.so.3:/lib/aarch64-linux-gnu/libdbus-1.so.3:ro
      - /lib/aarch64-linux-gnu/libdc1394.so.25:/lib/aarch64-linux-gnu/libdc1394.so.25:ro
      - /lib/aarch64-linux-gnu/libdecor-0.so.0:/lib/aarch64-linux-gnu/libdecor-0.so.0:ro
      - /lib/aarch64-linux-gnu/libdrm.so.2:/lib/aarch64-linux-gnu/libdrm.so.2:ro
      - /lib/aarch64-linux-gnu/libepoxy.so.0:/lib/aarch64-linux-gnu/libepoxy.so.0:ro
      - /lib/aarch64-linux-gnu/libFLAC.so.8:/lib/aarch64-linux-gnu/libFLAC.so.8:ro
      - /lib/aarch64-linux-gnu/libflite_cmulex.so.1:/lib/aarch64-linux-gnu/libflite_cmulex.so.1:ro
      - /lib/aarch64-linux-gnu/libflite_cmu_us_awb.so.1:/lib/aarch64-linux-gnu/libflite_cmu_us_awb.so.1:ro
      - /lib/aarch64-linux-gnu/libflite_cmu_us_kal16.so.1:/lib/aarch64-linux-gnu/libflite_cmu_us_kal16.so.1:ro
      - /lib/aarch64-linux-gnu/libflite_cmu_us_kal.so.1:/lib/aarch64-linux-gnu/libflite_cmu_us_kal.so.1:ro
      - /lib/aarch64-linux-gnu/libflite_cmu_us_rms.so.1:/lib/aarch64-linux-gnu/libflite_cmu_us_rms.so.1:ro
      - /lib/aarch64-linux-gnu/libflite_cmu_us_slt.so.1:/lib/aarch64-linux-gnu/libflite_cmu_us_slt.so.1:ro
      - /lib/aarch64-linux-gnu/libflite.so.1:/lib/aarch64-linux-gnu/libflite.so.1:ro
      - /lib/aarch64-linux-gnu/libflite_usenglish.so.1:/lib/aarch64-linux-gnu/libflite_usenglish.so.1:ro
      - /lib/aarch64-linux-gnu/libgbm.so.1:/lib/aarch64-linux-gnu/libgbm.so.1:ro
      - /lib/aarch64-linux-gnu/libgfortran.so.5:/lib/aarch64-linux-gnu/libgfortran.so.5:ro
      - /lib/aarch64-linux-gnu/libGLdispatch.so.0:/lib/aarch64-linux-gnu/libGLdispatch.so.0:ro
      - /lib/aarch64-linux-gnu/libGL.so.1:/lib/aarch64-linux-gnu/libGL.so.1:ro
      - /lib/aarch64-linux-gnu/libGLX.so.0:/lib/aarch64-linux-gnu/libGLX.so.0:ro
      - /lib/aarch64-linux-gnu/libgme.so.0:/lib/aarch64-linux-gnu/libgme.so.0:ro
      - /lib/aarch64-linux-gnu/libgsm.so.1:/lib/aarch64-linux-gnu/libgsm.so.1:ro
      - /lib/aarch64-linux-gnu/libiec61883.so.0:/lib/aarch64-linux-gnu/libiec61883.so.0:ro
      - /lib/aarch64-linux-gnu/libjack.so.0:/lib/aarch64-linux-gnu/libjack.so.0:ro
      - /lib/aarch64-linux-gnu/libjpeg.so.8:/lib/aarch64-linux-gnu/libjpeg.so.8:ro
      - /lib/aarch64-linux-gnu/liblapack.so.3:/lib/aarch64-linux-gnu/liblapack.so.3:ro
      - /lib/aarch64-linux-gnu/liblilv-0.so.0:/lib/aarch64-linux-gnu/liblilv-0.so.0:ro
      - /lib/aarch64-linux-gnu/libmbedcrypto.so.7:/lib/aarch64-linux-gnu/libmbedcrypto.so.7:ro
      - /lib/aarch64-linux-gnu/libmp3lame.so.0:/lib/aarch64-linux-gnu/libmp3lame.so.0:ro
      - /lib/aarch64-linux-gnu/libmpg123.so.0:/lib/aarch64-linux-gnu/libmpg123.so.0:ro
      - /lib/aarch64-linux-gnu/libmysofa.so.1:/lib/aarch64-linux-gnu/libmysofa.so.1:ro
      - /lib/aarch64-linux-gnu/libnorm.so.1:/lib/aarch64-linux-gnu/libnorm.so.1:ro
      - /lib/aarch64-linux-gnu/libogg.so.0:/lib/aarch64-linux-gnu/libogg.so.0:ro
      - /lib/aarch64-linux-gnu/libopenal.so.1:/lib/aarch64-linux-gnu/libopenal.so.1:ro
      - /lib/aarch64-linux-gnu/libOpenCL.so.1:/lib/aarch64-linux-gnu/libOpenCL.so.1:ro
      - /lib/aarch64-linux-gnu/libopenmpt.so.0:/lib/aarch64-linux-gnu/libopenmpt.so.0:ro
      - /lib/aarch64-linux-gnu/libopus.so.0:/lib/aarch64-linux-gnu/libopus.so.0:ro
      - /lib/aarch64-linux-gnu/libpgm-5.3.so.0:/lib/aarch64-linux-gnu/libpgm-5.3.so.0:ro
      - /lib/aarch64-linux-gnu/libplacebo.so.192:/lib/aarch64-linux-gnu/libplacebo.so.192:ro
      - /lib/aarch64-linux-gnu/libpocketsphinx.so.3:/lib/aarch64-linux-gnu/libpocketsphinx.so.3:ro
      - /lib/aarch64-linux-gnu/libpulsecommon-15.99.so:/lib/aarch64-linux-gnu/libpulsecommon-15.99.so:ro
      - /lib/aarch64-linux-gnu/libpulse.so.0:/lib/aarch64-linux-gnu/libpulse.so.0:ro
      - /lib/aarch64-linux-gnu/librabbitmq.so.4:/lib/aarch64-linux-gnu/librabbitmq.so.4:ro
      - /lib/aarch64-linux-gnu/libraw1394.so.11:/lib/aarch64-linux-gnu/libraw1394.so.11:ro
      - /lib/aarch64-linux-gnu/librga.so.2:/lib/aarch64-linux-gnu/librga.so.2:ro
      - /lib/aarch64-linux-gnu/librist.so.4:/lib/aarch64-linux-gnu/librist.so.4:ro
      - /lib/aarch64-linux-gnu/librockchip_mpp.so.1:/lib/aarch64-linux-gnu/librockchip_mpp.so.1:ro
      - /lib/aarch64-linux-gnu/librom1394.so.0:/lib/aarch64-linux-gnu/librom1394.so.0:ro
      - /lib/aarch64-linux-gnu/librubberband.so.2:/lib/aarch64-linux-gnu/librubberband.so.2:ro
      - /lib/aarch64-linux-gnu/libsamplerate.so.0:/lib/aarch64-linux-gnu/libsamplerate.so.0:ro
      - /lib/aarch64-linux-gnu/libSDL2-2.0.so.0:/lib/aarch64-linux-gnu/libSDL2-2.0.so.0:ro
      - /lib/aarch64-linux-gnu/libserd-0.so.0:/lib/aarch64-linux-gnu/libserd-0.so.0:ro
      - /lib/aarch64-linux-gnu/libshine.so.3:/lib/aarch64-linux-gnu/libshine.so.3:ro
      - /lib/aarch64-linux-gnu/libslang.so.2:/lib/aarch64-linux-gnu/libslang.so.2:ro
      - /lib/aarch64-linux-gnu/libsnappy.so.1:/lib/aarch64-linux-gnu/libsnappy.so.1:ro
      - /lib/aarch64-linux-gnu/libsndfile.so.1:/lib/aarch64-linux-gnu/libsndfile.so.1:ro
      - /lib/aarch64-linux-gnu/libsndio.so.7:/lib/aarch64-linux-gnu/libsndio.so.7:ro
      - /lib/aarch64-linux-gnu/libsodium.so.23:/lib/aarch64-linux-gnu/libsodium.so.23:ro
      - /lib/aarch64-linux-gnu/libsord-0.so.0:/lib/aarch64-linux-gnu/libsord-0.so.0:ro
      - /lib/aarch64-linux-gnu/libsoxr.so.0:/lib/aarch64-linux-gnu/libsoxr.so.0:ro
      - /lib/aarch64-linux-gnu/libspeex.so.1:/lib/aarch64-linux-gnu/libspeex.so.1:ro
      - /lib/aarch64-linux-gnu/libsphinxbase.so.3:/lib/aarch64-linux-gnu/libsphinxbase.so.3:ro
      - /lib/aarch64-linux-gnu/libsratom-0.so.0:/lib/aarch64-linux-gnu/libsratom-0.so.0:ro
      - /lib/aarch64-linux-gnu/libsrt-gnutls.so.1.4:/lib/aarch64-linux-gnu/libsrt-gnutls.so.1.4:ro
      - /lib/aarch64-linux-gnu/libssh-gcrypt.so.4:/lib/aarch64-linux-gnu/libssh-gcrypt.so.4:ro
      - /lib/aarch64-linux-gnu/libSvtAv1Enc.so.0:/lib/aarch64-linux-gnu/libSvtAv1Enc.so.0:ro
      - /lib/aarch64-linux-gnu/libswresample.so.3:/lib/aarch64-linux-gnu/libswresample.so.3:ro
      - /lib/aarch64-linux-gnu/libtheoradec.so.1:/lib/aarch64-linux-gnu/libtheoradec.so.1:ro
      - /lib/aarch64-linux-gnu/libtheoraenc.so.1:/lib/aarch64-linux-gnu/libtheoraenc.so.1:ro
      - /lib/aarch64-linux-gnu/libtwolame.so.0:/lib/aarch64-linux-gnu/libtwolame.so.0:ro
      - /lib/aarch64-linux-gnu/libudfread.so.0:/lib/aarch64-linux-gnu/libudfread.so.0:ro
      - /lib/aarch64-linux-gnu/libusb-1.0.so.0:/lib/aarch64-linux-gnu/libusb-1.0.so.0:ro
      - /lib/aarch64-linux-gnu/libva-drm.so.2:/lib/aarch64-linux-gnu/libva-drm.so.2:ro
      - /lib/aarch64-linux-gnu/libva.so.2:/lib/aarch64-linux-gnu/libva.so.2:ro
      - /lib/aarch64-linux-gnu/libva-x11.so.2:/lib/aarch64-linux-gnu/libva-x11.so.2:ro
      - /lib/aarch64-linux-gnu/libvdpau.so.1:/lib/aarch64-linux-gnu/libvdpau.so.1:ro
      - /lib/aarch64-linux-gnu/libvidstab.so.1.1:/lib/aarch64-linux-gnu/libvidstab.so.1.1:ro
      - /lib/aarch64-linux-gnu/libvorbisenc.so.2:/lib/aarch64-linux-gnu/libvorbisenc.so.2:ro
      - /lib/aarch64-linux-gnu/libvorbisfile.so.3:/lib/aarch64-linux-gnu/libvorbisfile.so.3:ro
      - /lib/aarch64-linux-gnu/libvorbis.so.0:/lib/aarch64-linux-gnu/libvorbis.so.0:ro
      - /lib/aarch64-linux-gnu/libvpx.so.7:/lib/aarch64-linux-gnu/libvpx.so.7:ro
      - /lib/aarch64-linux-gnu/libvulkan.so.1:/lib/aarch64-linux-gnu/libvulkan.so.1:ro
      - /lib/aarch64-linux-gnu/libwayland-client.so.0:/lib/aarch64-linux-gnu/libwayland-client.so.0:ro
      - /lib/aarch64-linux-gnu/libwayland-cursor.so.0:/lib/aarch64-linux-gnu/libwayland-cursor.so.0:ro
      - /lib/aarch64-linux-gnu/libwayland-egl.so.1:/lib/aarch64-linux-gnu/libwayland-egl.so.1:ro
      - /lib/aarch64-linux-gnu/libwayland-server.so.0:/lib/aarch64-linux-gnu/libwayland-server.so.0:ro
      - /lib/aarch64-linux-gnu/libX11-xcb.so.1:/lib/aarch64-linux-gnu/libX11-xcb.so.1:ro
      - /lib/aarch64-linux-gnu/libx264.so.163:/lib/aarch64-linux-gnu/libx264.so.163:ro
      - /lib/aarch64-linux-gnu/libxcb-shape.so.0:/lib/aarch64-linux-gnu/libxcb-shape.so.0:ro
      - /lib/aarch64-linux-gnu/libxcb-xfixes.so.0:/lib/aarch64-linux-gnu/libxcb-xfixes.so.0:ro
      - /lib/aarch64-linux-gnu/libXcursor.so.1:/lib/aarch64-linux-gnu/libXcursor.so.1:ro
      - /lib/aarch64-linux-gnu/libXfixes.so.3:/lib/aarch64-linux-gnu/libXfixes.so.3:ro
      - /lib/aarch64-linux-gnu/libXinerama.so.1:/lib/aarch64-linux-gnu/libXinerama.so.1:ro
      - /lib/aarch64-linux-gnu/libXi.so.6:/lib/aarch64-linux-gnu/libXi.so.6:ro
      - /lib/aarch64-linux-gnu/libxkbcommon.so.0:/lib/aarch64-linux-gnu/libxkbcommon.so.0:ro
      - /lib/aarch64-linux-gnu/libXrandr.so.2:/lib/aarch64-linux-gnu/libXrandr.so.2:ro
      - /lib/aarch64-linux-gnu/libXss.so.1:/lib/aarch64-linux-gnu/libXss.so.1:ro
      - /lib/aarch64-linux-gnu/libxvidcore.so.4:/lib/aarch64-linux-gnu/libxvidcore.so.4:ro
      - /lib/aarch64-linux-gnu/libXv.so.1:/lib/aarch64-linux-gnu/libXv.so.1:ro
      - /lib/aarch64-linux-gnu/libXxf86vm.so.1:/lib/aarch64-linux-gnu/libXxf86vm.so.1:ro
      - /lib/aarch64-linux-gnu/libyuv.so.0:/lib/aarch64-linux-gnu/libyuv.so.0:ro
      - /lib/aarch64-linux-gnu/libzimg.so.2:/lib/aarch64-linux-gnu/libzimg.so.2:ro
      - /lib/aarch64-linux-gnu/libzmq.so.5:/lib/aarch64-linux-gnu/libzmq.so.5:ro
      - /lib/aarch64-linux-gnu/libzvbi.so.0:/lib/aarch64-linux-gnu/libzvbi.so.0:ro
      - /lib/aarch64-linux-gnu/pulseaudio/libpulsecommon-15.99.so:/lib/aarch64-linux-gnu/pulseaudio/libpulsecommon-15.99.so:ro
