name: Docker

on:
  workflow_dispatch:
  push:
    branches: [kml]
  pull_request:
    branches: [kml]
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write

jobs:
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-latest
    strategy:
      # Prevent a failure in one image from stopping the other builds
      fail-fast: false
      matrix:
        include:
          - image: immich-machine-learning
            context: machine-learning
            file: machine-learning/Dockerfile
            platforms: linux/arm64
            device: cpu

          - image: immich-machine-learning
            context: machine-learning
            file: machine-learning/Dockerfile
            platforms: linux/arm64
            device: armnn
            suffix: -armnn

          - image: immich-server
            context: .
            file: server/Dockerfile
            platforms: linux/arm64
            device: cpu

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5.3.0
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          platforms: ${{ matrix.platforms }}
          push: true
          build-args: |
            DEVICE=${{ matrix.device }}
          tags: ${{ secrets.BETA_REPO_URL }}:immich

